/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-19 10:55:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lec05_005fboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/IT/S3917_J11/workspace_sts3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring3_prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/IT/S3917_J11/workspace_sts3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring3_prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1718068926195L));
    _jspx_dependants.put("jar:file:/C:/IT/S3917_J11/workspace_sts3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring3_prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <title>Tables - SB Admin</title>\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- --------------------------------------- 게시물 상세보기 ------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("<form id=\"boardForm\" >\r\n");
      out.write("<input type=\"hidden\" name=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"regid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.regid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("   <th width=\"20%\">글번호</th>\r\n");
      out.write("   <td width=\"80%\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("      <th>작성자</th>\r\n");
      out.write("      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.regid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("      <th>작성일</th>\r\n");
      out.write("      <td><input type=\"text\" name=\"regdate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("      <th>제목</th>\r\n");
      out.write("      <td><input type=\"text\" name=\"title\" size=60  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("      <th>내용</th>\r\n");
      out.write("      <td><textarea name=\"contents\" cols=\"80\" rows=\"6\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=2 align=\"center\">\r\n");
      out.write("		<input type=\"button\" id=\"uptButton\" value=\"수정\">\r\n");
      out.write("		<input type=\"button\" id=\"delButton\"  value=\"삭제\">\r\n");
      out.write("		<input type=\"button\" id=\"listButton\" value=\"목록\">\r\n");
      out.write("	</td>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<!-- --------------------------------------- 댓글목록 ------------------------------- -->\r\n");
      out.write("<br>\r\n");
      out.write("<div id=\"replyListDiv\">\r\n");
      out.write("	<table width=100% border=1>\r\n");
      out.write("		<tr><td></td></tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- --------------------------------------- 댓글등록 ------------------------------- -->\r\n");
      out.write("<br>\r\n");
      out.write("<form method=\"post\" id=\"replyInsertForm\">\r\n");
      out.write("<input type=hidden name=seq id=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<table width=100% border=1>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("		<input type=\"text\" size=100 name=\"reply\" id=\"reply\">\r\n");
      out.write("		<input type=\"button\"  id=\"replyInsertBtn\" value=\"댓글등록\">\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			function makeTable() {\r\n");
      out.write("				\r\n");
      out.write("				//화면 준비되면 댓글목록 바로 가져오기 :::  REST\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					method      : \"POST\",\r\n");
      out.write("			        url         : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply_list_rest\",\r\n");
      out.write("			        contentType : \"application/x-www-form-urlencoded; charset=UTF-8\",\r\n");
      out.write("			        data 		: \"seq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${KEY_BOARDVO.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",   \r\n");
      out.write("			  		error 	    : function(myval){ console.log(\"에러:\" + myval);   },\r\n");
      out.write("			  		success     : function(myval){ \r\n");
      out.write("			  										console.log(\"성공:\" + myval);  //ResponseEntity<>(rlist, HttpStatus.OK)   \r\n");
      out.write("			  										\r\n");
      out.write("			  										var htmlStr = \"<table border=1 width=50%>\";\r\n");
      out.write("			  										$.map( myval, function( MYval, MYidx ) {\r\n");
      out.write("			  											htmlStr += \"<tr><td><font color='red'><input type='button' id='replyDeleteBtn' value='[X]' data-rseq='\" + MYval.rseq + \"' data-seq='\" + MYval.seq + \"'></font>\" + MYval.reply + \"</td></tr>\";\r\n");
      out.write("\r\n");
      out.write("			  											//console.log(MYval[\"title\"] + \",\" + MYval[\"regid\"] + \",\" + MYidx);\r\n");
      out.write("			  										});\r\n");
      out.write("			  										htmlStr += \"</table>\";\r\n");
      out.write("			  										$(\"#replyListDiv\").empty();\r\n");
      out.write("			  										$(\"#replyListDiv\").html(htmlStr);\r\n");
      out.write("			  										\r\n");
      out.write("			  									}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			//화면이 실행되자마자 댓글목록 가져오기 :: REST\r\n");
      out.write("			makeTable();\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			//댓글 입력 :: REST\r\n");
      out.write("			$(\"#replyInsertBtn\").click(  function(){\r\n");
      out.write("				var formData = $(\"#replyInsertForm\").serialize();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					method      : \"POST\",\r\n");
      out.write("			        url         : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply_insert_rest\",\r\n");
      out.write("			        contentType : \"application/x-www-form-urlencoded; charset=UTF-8\",\r\n");
      out.write("			        //data 		: \"seq=\" +$(\"#seq\").val()+\"&reply=\" + $(\"#reply\").val(),   \r\n");
      out.write("			  		data 		: formData,\r\n");
      out.write("			        error 	    : function(myval){ console.log(\"에러:\" + myval);   },\r\n");
      out.write("			  		success     : function(myval){ \r\n");
      out.write("			  										console.log(\"성공:\" + myval);  //msg = \"입력성공\"   \r\n");
      out.write("			  										makeTable();\r\n");
      out.write("			  									}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			//댓글 삭제 :: REST\r\n");
      out.write("					$(document).on(\"click\", \"#replyDeleteBtn\", function() {\r\n");
      out.write("						var rseq = $(this).data(\"rseq\");\r\n");
      out.write("					    var seq = $(this).data(\"seq\");\r\n");
      out.write("					    var formData = { rseq: rseq, seq: seq }; // formData 정의\r\n");
      out.write("					    \r\n");
      out.write("		    $.ajax({\r\n");
      out.write("		        method: \"POST\",\r\n");
      out.write("		        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply_delete_rest\",\r\n");
      out.write("		        contentType: \"application/x-www-form-urlencoded; charset=UTF-8\",\r\n");
      out.write("		        data: formData,\r\n");
      out.write("		        error: function(myval) {\r\n");
      out.write("		            console.log(\"에러:\" + myval);\r\n");
      out.write("		        },\r\n");
      out.write("		        success: function(myval) {\r\n");
      out.write("		            console.log(\"삭제성공:\" + myval);\r\n");
      out.write("		            makeTable();\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("});\r\n");
      out.write("			$(\"#uptButton\").click(  function(){\r\n");
      out.write("				alert(\"수정\");\r\n");
      out.write("				$(\"#boardForm\").attr(\"method\",\"post\");\r\n");
      out.write("				$(\"#boardForm\").attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board_update\");\r\n");
      out.write("				$(\"#boardForm\").submit();\r\n");
      out.write("				return true;\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#delButton\").click(  function(){\r\n");
      out.write("				alert(\"삭제\");\r\n");
      out.write("				$(\"#boardForm\").attr(\"method\",\"post\");\r\n");
      out.write("				$(\"#boardForm\").attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board_delete\");\r\n");
      out.write("				$(\"#boardForm\").submit();\r\n");
      out.write("				return true;\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#listButton\").click(  function(){\r\n");
      out.write("				location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board_list\";\r\n");
      out.write("			});            \r\n");
      out.write("			\r\n");
      out.write("			//------------------------------------------------------------\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
